aggregator_kwargs:
  d_z: 88
  init_data:
  - 0.0
  - 1.0
aggregator_type: BayesianAggregator
d_x: 1
d_y: 1
d_z: 88
decoder_kwargs:
  arch: separate_networks_separate_input
  d_x: 1
  d_y: 1
  d_z: 88
  f_act: tanh
  mlp_layers_mu_y:
  - 115
  - 44
  mlp_layers_std_y:
  - 75
  - 60
  - 44
  safe_log: 1.0e-08
  seed: 1234
decoder_type: DecoderNetworkPB
encoder_kwargs:
  arch: separate_networks
  d_lo: 88
  d_x: 1
  d_y: 1
  f_act: tanh
  mlp_layers_cov_r:
  - 171
  - 124
  - 76
  mlp_layers_r:
  - 48
  seed: 1234
encoder_type: EncoderNetworkBA
seed: 1234
training:
  adam_lr: 0.000402238
  batch_size: 16
  device: cuda
  loss_kwargs: {}
  loss_type: PB
  n_context_meta_max: 50
  n_context_meta_min: 3
  n_context_val_max: 50
  n_context_val_min: 0
  save_interval: 100
  seed: 1234
  validation_interval: 10
