aggregator_kwargs:
  d_lo: 56
  d_z: 56
  f_act: tanh
  init_data:
  - 1.0
  - 0
  mlp_layers:
  - 56
  seed: 1234
aggregator_type: MeanAggregatorRtoZ
d_x: 1
d_y: 1
d_z: 56
decoder_kwargs:
  arch: separate_networks
  d_x: 1
  d_y: 1
  d_z: 56
  f_act: tanh
  mlp_layers_mu_y:
  - 115
  mlp_layers_std_y:
  - 156
  - 113
  - 70
  - 27
  seed: 1234
decoder_type: DecoderNetworkSamples
encoder_kwargs:
  d_lo: 56
  d_x: 1
  d_y: 1
  f_act: tanh
  mlp_layers:
  - 143
  - 95
  - 46
  seed: 1234
encoder_type: EncoderNetworkMA
seed: 1234
training:
  adam_lr: 0.00124918
  batch_size: 16
  device: cuda
  loss_kwargs:
    n_marg: 10
  loss_type: VI
  n_context_meta_max: 50
  n_context_meta_min: 3
  n_context_val_max: 50
  n_context_val_min: 0
  save_interval: 100
  seed: 1234
  validation_interval: 10
