aggregator_kwargs:
  d_z: 38
  init_data:
  - 0.0
  - 1.0
aggregator_type: BayesianAggregator
d_x: 1
d_y: 1
d_z: 38
decoder_kwargs:
  arch: separate_networks_separate_input
  d_x: 1
  d_y: 1
  d_z: 38
  f_act: tanh
  mlp_layers_mu_y:
  - 81
  - 55
  - 28
  - 2
  mlp_layers_std_y:
  - 175
  - 60
  safe_log: 1.0e-08
  seed: 1234
decoder_type: DecoderNetworkPB
encoder_kwargs:
  arch: separate_networks
  d_lo: 38
  d_x: 1
  d_y: 1
  f_act: tanh
  mlp_layers_cov_r:
  - 32
  - 60
  - 89
  - 117
  mlp_layers_r:
  - 15
  - 19
  - 24
  - 28
  - 32
  seed: 1234
encoder_type: EncoderNetworkBA
seed: 1234
training:
  adam_lr: 0.00114412
  batch_size: 16
  device: cuda
  loss_kwargs: {}
  loss_type: PB
  n_context_meta_max: 50
  n_context_meta_min: 3
  n_context_val_max: 50
  n_context_val_min: 0
  save_interval: 100
  seed: 1234
  validation_interval: 10
