aggregator_kwargs:
  d_lo: 83
  init_data:
  - 1.0
  - 0
aggregator_type: MeanAggregator
d_x: 1
d_y: 1
d_z: 83
decoder_kwargs:
  arch: separate_networks
  d_x: 1
  d_y: 1
  d_z: 83
  f_act: tanh
  mlp_layers_mu_y:
  - 168
  - 118
  - 69
  - 19
  mlp_layers_std_y:
  - 83
  - 70
  seed: 1234
decoder_type: DecoderNetworkSamples
encoder_kwargs:
  d_lo: 83
  d_x: 1
  d_y: 1
  f_act: tanh
  mlp_layers:
  - 71
  - 99
  - 126
  seed: 1234
encoder_type: EncoderNetworkMA
seed: 1234
training:
  adam_lr: 0.000743227
  batch_size: 16
  device: cuda
  loss_kwargs: {}
  loss_type: PB
  n_context_meta_max: 50
  n_context_meta_min: 3
  n_context_val_max: 50
  n_context_val_min: 0
  save_interval: 100
  seed: 1234
  validation_interval: 10
