aggregator_kwargs:
  d_z: 68
  init_data:
  - 0.0
  - 1.0
aggregator_type: BayesianAggregator
d_x: 1
d_y: 1
d_z: 68
decoder_kwargs:
  arch: separate_networks_separate_input
  d_x: 1
  d_y: 1
  d_z: 68
  f_act: tanh
  mlp_layers_mu_y:
  - 76
  - 68
  - 61
  - 53
  mlp_layers_std_y:
  - 66
  - 60
  - 54
  - 47
  - 41
  safe_log: 1.0e-08
  seed: 1234
decoder_type: DecoderNetworkPB
encoder_kwargs:
  arch: separate_networks
  d_lo: 68
  d_x: 1
  d_y: 1
  f_act: tanh
  mlp_layers_cov_r:
  - 94
  - 71
  - 47
  mlp_layers_r:
  - 43
  seed: 1234
encoder_type: EncoderNetworkBA
seed: 1234
training:
  adam_lr: 0.000583953
  batch_size: 16
  device: cuda
  loss_kwargs: {}
  loss_type: PB
  n_context_meta_max: 50
  n_context_meta_min: 3
  n_context_val_max: 50
  n_context_val_min: 0
  save_interval: 100
  seed: 1234
  validation_interval: 10
