aggregator_kwargs:
  d_z: 13
  init_data:
  - 0.0
  - 1.0
aggregator_type: BayesianAggregator
d_x: 1
d_y: 1
d_z: 13
decoder_kwargs:
  arch: separate_networks
  d_x: 1
  d_y: 1
  d_z: 13
  f_act: tanh
  mlp_layers_mu_y:
  - 132
  - 35
  mlp_layers_std_y:
  - 90
  - 81
  - 71
  seed: 1234
decoder_type: DecoderNetworkSamples
encoder_kwargs:
  arch: separate_networks
  d_lo: 13
  d_x: 1
  d_y: 1
  f_act: tanh
  mlp_layers_cov_r:
  - 60
  - 124
  - 187
  mlp_layers_r:
  - 81
  - 59
  - 36
  seed: 1234
encoder_type: EncoderNetworkBA
seed: 1234
training:
  adam_lr: 0.000259562
  batch_size: 16
  device: cuda
  loss_kwargs:
    n_marg: 10
  loss_type: VI
  n_context_meta_max: 50
  n_context_meta_min: 3
  n_context_val_max: 50
  n_context_val_min: 0
  save_interval: 100
  seed: 1234
  validation_interval: 10
